In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()
x = dataset.data
y = dataset.target
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [3]:
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [4]:
n_samples, n_features = x.shape
print(f'Samples in dataset = {n_samples}')
print(f'Features in dataset = {n_features}')

Samples in dataset = 150
Features in dataset = 4


In [5]:
attribute_means = x.mean(axis=0)
assert attribute_means.shape == (n_features,)
x_d = np.array(x >= attribute_means, dtype='int')
print(x_d)

[[0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 1 1]
 [1 0 1 1]
 [0 0 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 0 1 1]
 [0 0 1 1]
 [0 0 0 0]
 [1 0 1 1]
 [1 0 1 0]
 [1 0 1 1]
 [0 0 0 1]
 [1 1 1 1]
 [0 0 1 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 0 1 0]
 [1 1 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 1 1]
 [1 0 1 1]
 [0 0 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 0 1 1]
 [0 0 1 1]
 [0 0 1 1]
 [0 0 1 1]

In [6]:
# Necessary imports that we will use to create a function that computes class prediction and error for specific feature value
from collections import defaultdict
from operator import itemgetter

In [7]:
def train_feature_value(x, y_true, feature, value):
    # Create a simple dictionary to count how frequency they give certain predictions
    class_counts = defaultdict(int)
    
    # Iterate through each sample and count the frequency of each class/value pair
    for sample, y in zip(x, y_true):
        if sample[feature] == value:
            class_counts[y] += 1
    
    # Now get the best one by sorting (highest first) and choosing the first item
    sorted_class_counts = sorted(class_counts.items(), key=itemgetter(1), reverse=True)
    most_frequent_class = sorted_class_counts[0][0]
    
    # The error is the number of samples that do not classify as the most frequent class and have the feature value
    n_samples = x.shape[1]
    error = sum([class_count for class_value, class_count in class_counts.items()
                if class_value != most_frequent_class])
    return most_frequent_class, error


In [8]:
def train(x, y_true, feature):
    # Check that variable is a valid number
    n_samples, n_features = x.shape
    assert 0 <= feature < n_features
    
    # Get all of the unique values that this variable has
    values = set(x[:,feature])
    
    # Stores the predictors array that is returned
    predictors = dict()
    errors = []
    for current_value in values:
        most_frequent_class, error = train_feature_value(x, y_true, feature, current_value)
        predictors[current_value] = most_frequent_class
        errors.append(error)
    
    # Compute the total error of using this feature to classify on
    total_error = sum(errors)
    return predictors, total_error
        

In [9]:
# Splitting dataset into small datasets: training and testing
from sklearn.model_selection import train_test_split

In [10]:
# Creating datasets for training and testing
xd_train, xd_test, y_train, y_test = train_test_split(x_d, y, random_state=14)
print(f'There are {y_train.shape} training sets')
print(f'There are {y_test.shape} testing sets')

There are (112,) training sets
There are (38,) testing sets


In [11]:
# Computing the predictors for all the features for out dataset
all_predictors = {}
errors = {}
for feature_index in range(xd_train.shape[1]):
    predictors, total_error = train(xd_train, y_train, feature_index)
    all_predictors[feature_index] = predictors
    errors[feature_index] = total_error
print(all_predictors)
print(errors)

{0: {0: 0, 1: 2}, 1: {0: 1, 1: 0}, 2: {0: 0, 1: 2}, 3: {0: 0, 1: 2}}
{0: 41, 1: 58, 2: 37, 3: 37}


In [12]:
# Next, we find the best feature to use our One Rule by finding the feature with the lowest error
best_feature, best_error = sorted(errors.items(), key=itemgetter(1))[0]
print(best_feature)
print(best_error)

2
37


In [13]:
# Creating our model by storing the predictors for the best feature
model = {'feature': best_feature, 'predictor': all_predictors[best_feature]}
print(model)


{'feature': 2, 'predictor': {0: 0, 1: 2}}


In [14]:
# Defining a function that can predict several new samples at one time
def predict(x_test, model):
    variable = model['feature']
    predictor = model['predictor']
    y_predicted = np.array([predictor[int(sample[variable])]
                            for sample in x_test])
    return y_predicted

In [15]:
# Getting predictions of testing dataset
y_predicted = predict(xd_test, model)
print(y_predicted)

[0 0 0 2 2 2 0 2 0 2 2 0 2 2 0 2 0 2 2 2 0 0 0 2 0 2 0 2 2 0 0 0 2 0 2 0 2
 2]


In [16]:
# Computing accuracy of this testing dataset by comparing it to the known classes
accuracy = np.mean(y_predicted == y_test) * 100
print(f'The test accuracy is {accuracy:.1f}%')

The test accuracy is 65.8%
